---
name: Ansible Test Sanity

on:
  workflow_call:  # allow this workflow to be called from other workflows
  workflow_dispatch:  # allow this workflow to be called from user
  # Schedule run (once daily)
  schedule:
    ## Daily Docker Image Rebuild (10:29am daily)
    - cron: '29 10 * * *'

jobs:
  ansible_test_sanity:
    name: Perform sanity testing
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # Ansible Support Matrix
        # https://docs.ansible.com/ansible/latest/reference_appendices/release_and_maintenance.html#ansible-core-support-matrix
        versions:
          # Testing all ansible and python versions is impractical. Only test the newest and
          # oldest versions of each that we support
          - { python: "3.13", ansible: stable-2.19 }
          - { python: "3.11", ansible: stable-2.19 }
          - { python: "3.12", ansible: stable-2.16 }
          - { python: "3.10", ansible: stable-2.16 }
#          - { python: "3.13", ansible: devel }

    steps:
      # Run sanity tests inside a Docker container.
      # The docker container has all the pinned dependencies that are
      # required and all Python versions Ansible supports.
      #      - name: Perform sanity testing with (${{ matrix.versions.ansible }}+py${{ matrix.versions.python }})
      - name: >-
          Perform sanity testing against
          Ansible version ${{ matrix.versions.ansible }}
          under Python ${{ matrix.versions.python }}
        # See the documentation for the following GitHub action on
        # https://github.com/ansible-community/ansible-test-gh-action/blob/main/README.md
        uses: ansible-community/ansible-test-gh-action@release/v1
        with:
#          args: '-vvv'
          ansible-core-version: ${{ matrix.versions.ansible }}
          target-python-version: ${{ matrix.versions.python }}
          testing-type: sanity
#          test-deps: >-
#            dettonville.utils
          pull-request-change-detection: false
          coverage: never # coverage is always very low for sanity tests, and doesn't make much sense
          pre-test-cmd: >-
            ansible --version
#          pre-test-cmd: >-
#            export -p | sed 's/declare -x //' | sed 's/export //'

  # This job does nothing and is only used for the branch protection
  # or multi-stage CI jobs, like making sure that all tests pass before
  # a publishing job is started.
  sanity-check:
    if: always()
    needs:
      - ansible_test_sanity
    runs-on: ubuntu-latest
    steps:
      - name: Decide whether the needed jobs succeeded or failed
        uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}
